require('tests.helpers').setup_plugin()
local float = require('luxdash.ui.float_manager')

describe('floating dashboard lifecycle', function()
  local origin, buf, config
  before_each(function()
    origin, buf = vim.api.nvim_get_current_win(), vim.api.nvim_get_current_buf()
    config = require('luxdash').config
    require('luxdash').config = vim.deepcopy(config)
    require('luxdash').config.logo = { 'Dashboard' }
    float.setup({ hide_buffer = true })
  end)
  after_each(function()
    float.close()
    vim.wait(30, function() return false end)
    require('luxdash').config = config
    vim.api.nvim_set_current_win(origin)
    vim.api.nvim_win_set_buf(origin, buf)
  end)

  it('renders with its own context and returns to the original editing window', function()
    float.toggle()
    local win, dashboard = vim.api.nvim_get_current_win(), vim.api.nvim_get_current_buf()
    assert.is_true(vim.wait(500, function() return vim.api.nvim_buf_line_count(dashboard) > 1 end))
    assert.equals('luxdash', vim.bo[dashboard].filetype)
    float.resize()
    assert.equals(win, vim.api.nvim_get_current_win())
    float.close()
    assert.equals(origin, vim.api.nvim_get_current_win())
    assert.equals(buf, vim.api.nvim_get_current_buf())
  end)

  it('ignores scheduled rendering for a float that was closed and reopened', function()
    float.open()
    float.close()
    local win, dashboard = float.open()
    assert.is_true(vim.wait(500, function() return vim.api.nvim_buf_line_count(dashboard) > 1 end))
    assert.equals(win, vim.api.nvim_get_current_win())
    assert.equals(dashboard, vim.api.nvim_get_current_buf())
    assert.equals(buf, vim.api.nvim_win_get_buf(origin))
  end)

  it('keeps cleanup from restoring a float buffer over a selected recent file', function()
    local file = vim.fn.tempname() .. ' file.lua'
    vim.fn.writefile({ 'return true' }, file)
    local _, dashboard = float.open()
    vim.wait(30, function() return false end)
    require('luxdash.sections.recent_files').setup_file_keymap(1, file, dashboard)
    vim.cmd('normal 1')
    vim.wait(30, function() return false end)
    assert.equals(origin, vim.api.nvim_get_current_win())
    assert.equals(file, vim.api.nvim_buf_get_name(0))
    assert.is_false(float.is_open())
    vim.cmd('bdelete!')
    vim.fn.delete(file)
  end)
end)
